import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Chess } from "chess.js";
import { Chessboard } from "react-chessboard";

interface Move {
	from: string;
	to: string;
	promotion?: string;
}

export default function Home() {
	const [game, setGame] = useState<Chess>(new Chess());

	function makeAMove(move: Move) {
		let temp = new Chess(game.fen());
		console.log(move);
		let result = temp.move(move);
		setGame(temp);
		console.log(result);
		return result;
	}

	function onDrop(sourceSquare: string, targetSquare: string) {
		const move = makeAMove({
			from: sourceSquare,
			to: targetSquare,
			//promotion: "q", // always promote to a queen for example simplicity
		});

		// illegal move
		if (move === null) return false;
		//make a move here
		return true;
	}

	const onPiece = (piece: string) => {
		console.log(piece);
	};

	return (
		<div className="bg-gray-900 h-screen">
			<Head>
				<title>Chess</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-center text-white text-3xl font-bold  p-10">Chess</h1>
			<div className="flex justify-center items-center">
				<div className="w-96">
					<Chessboard
						id="BasicBoard"
						position={game.fen()}
						onPieceDrop={onDrop}
						onPieceClick={onPiece}
					/>
				</div>
			</div>
		</div>
	);
}
